from typing import TypedDict, Annotated
import operator

class AgentState(TypedDict):
    # Current observation and last action
    current_observation: dict                                   # JSON from Perception module (hypotheses about objects).
    last_action: dict                                           # JSON which was just generated by Decision.
    last_outcome: dict                                          # JSON outcome from the previous step (whether the expectation was confirmed)

    # Context for planning and learning
    short_term_memory: Annotated[list[dict], operator.add]      # A list of the last N triplets (observation, action, outcome). This is the Episodic Buffer.
    active_hypotheses: dict                                     # Current assumptions of World_model module

    # Internal drivers and meta-information
    internal_drives: dict                                       # curiosity, survival

    # ... others fields